name: Update

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      DB_CONNECTION: mysql
      DB_DATABASE: lyzzu
      DB_USERNAME: root
      DB_PASSWORD: root
      
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Clear cache
      run: php artisan optimize:clear
